### PR TITLE
Follow up responsive fixes for metric configuration

### LINKED ISSUE #438: Responsiveness followups [Metric Configuration][Design Blocking]
* I think we need to be more intentional with the spacing between prompts/sections. Right now, everything is blending together in a way that’s a little disorienting.
* No indication in the metric selection dropdown of which metric is currently selected.
* It would be neat to always know what you’re editing, regardless of your position on the page. Right now, it’s pretty easy to lose that context.

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Description here
Fixes for metric configuration responsive view

## Type of change
Type: Non-breaking refactor 

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #438 #436

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by ivan-kishko** [comment]
Hello to all guys. Made a PR as you can see for fixes of Metric Config page. Problem is that now since we have new breakpoint it looks ugly when width goes appx from 1200 to 860(new breakpoint). Maybe this problem is solved in coming metric config page new design. Anyway looking forward for your review. Thanks!)

**Review by lilidworkin — APPROVED** [review]
Seems like nobody had any major complaints (discussion in Slack [here](https://recidiviz.slack.com/archives/C04PH566YMP/p1678135240225689)) so @ivan-kishko you can go ahead and merge this! cc @mxosman if he wants to take a quick look and sanity check it, but I don't think we need to do super detailed review of these changes since they're all aesthetic and not functional.

File: publisher/src/components/MetricConfiguration/MetricConfiguration.tsx [hunk 1]
```diff
@@ -393,7 +402,7 @@ export const MetricConfiguration: React.FC = observer(() => {
                 </>
               )}
 
-              {windowWidth > MIN_DESKTOP_WIDTH && (
+              {windowWidth > MIN_TABLET_WIDTH && (
```
Comment (mxosman) [inline publisher/src/components/MetricConfiguration/MetricConfiguration.tsx:405]: This was totally my bad - I think these are duplicates. We can merge them into just one and remove the `windowWidth <= MIN_TABLET_WIDTH` &  `windowWidth > MIN_TABLET_WIDTH` conditionals (we don't need them any more, right?).

https://github.com/Recidiviz/justice-counts/blob/f1f078692050fdca2bf6ea653a8f125b89088358/publisher/src/components/MetricConfiguration/MetricConfiguration.tsx#L391-L417

**Comment by mxosman** [comment]
Awesome, Ivan! Nothing else from me except for a couple of tiny notes!

File: publisher/src/components/MetricConfiguration/MetricConfiguration.tsx (hunk 1 above)
Comment (ivan-kishko) [reply publisher/src/components/MetricConfiguration/MetricConfiguration.tsx:405]: we are because MetricBreakdownAvailabilityDefinitions is designed the way if there is no active dimension it will display metric definitions instead of breakdown ones so for mobile view there is another condition which is if activeDimensionKey is not undefined
