### PR TITLE
[Publisher] Gate create records route from non-admins

### LINKED ISSUE #1011: [Publisher] Gate `/reports/create` route from non-admins
There are cases where a user does not have a role assigned or has a READ ONLY role (or similar non-admin role) that does not allow a user to create a record. Currently, the Create Record button in the Records page is only visible to admin users, but it does not prevent access to the `/reports/create` route if a user goes to the URL directly or via a Create Record task card in the home page that links to the URL.

Two action items to accomplish this are:
* Gate the route from non-admin users (could add a simple redirect in the create users page)
* Add tooltip on the Home page Create Record task cards that reads: "You do not have permissions to create records, please reach out to your administrator for more assistance"

Inspired by this Sentry error: https://recidiviz-inc.sentry.io/issues/4559224133/?environment=production&project=4504532096516096&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

1. Added tooltip to Task Cards for read only users

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

closes #1011 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Hi @mxosman! Are we sure we don't gate it anywhere else? I'm trying to reach `/reports/create` and `/records/create` urls from read only user and can't do that.

**Comment by nasaownsky** [comment]
Hi @mxosman! Are we sure we weren't gate it anywhere else before? I'm trying to reach `/reports/create` and `/records/create` urls under read only user and can't do that.

File: publisher/src/components/Home/TaskCard.tsx [hunk 1]
```diff
@@ -54,8 +55,10 @@ export const TaskCard: React.FC<{
               action.label === taskCardLabelsActionLinks.uploadData.label
             )
               return;
+            const isReadOnlyCreateRecordTaskCard =
+              isUserReadOnly && action.path === "records/" && !recordID;
```
Comment (mxosman) [inline publisher/src/components/Home/TaskCard.tsx:59]: nit: Can we create enums/consts for the path names incase we need to change them for any reason? I was thinking defining them in this file https://github.com/Recidiviz/justice-counts/blob/nasaownsky/1011-gate-create-records/publisher/src/components/Home/types.ts - updating the `taskCardLabelsActionLinks` links there and importing the enum here.

File: publisher/src/components/Home/TaskCard.tsx [hunk 2]
```diff
@@ -54,8 +55,10 @@ export const TaskCard: React.FC<{
...
             const tooltipAnchorID =
-              action.path === "upload"
+              action.path === "upload" || isReadOnlyCreateRecordTaskCard
```
Comment (mxosman) [inline publisher/src/components/Home/TaskCard.tsx:61]: Out of curiosity, why do we need the `|| isReadOnlyCreateRecordTaskCard` here for the anchor id?

**Review by mxosman — COMMENTED** [review]
Thank you for working on this so quickly, @nasaownsky!

> Hi @mxosman! Are we sure we weren't gate it anywhere else before? I'm trying to reach `/reports/create` and `/records/create` urls under read only user and can't do that.

Oh you're absolutely right! We already implemented this - thanks for calling it out! I think what we didn't do was update the old ticket and the work you've done here (adding a tooltip to the buttons that take you there).

Sorry I didn't call this out before in the ticket - I just thought of it; but one thing that would be nice to implement is disabling those links on the cards and adjusting the color to be grey, just to avoid the redirecting all together.

One other thing worth addressing - it looks like there are two tooltips overlapping each other - the new one and the old one. It's hard to notice unless you look close or see the quick millisecond switch when you're hovering over them. Can you take another look at that?
Screenshot 2025-01-27 at 1 09 13 PM

File: publisher/src/components/Home/TaskCard.tsx (hunk 2 above)
Comment (nasaownsky) [reply publisher/src/components/Home/TaskCard.tsx]: So because of the condition `action.path === "upload"` we will create `tooltipAnchorID` only for upload path, but for the second tooltip we need it for `/records` path.

**Comment by nasaownsky** [comment]
@mxosman I also noticed that for the read only users we have task cards with `Manual Entry` buttons that lead us to `agency/:agencyID/records/:recordID` pages, where they actually can't manual entry anything, but can see already existed existed data. Maybe rename `Manual Entry` in this cases?

File: publisher/src/components/Home/TaskCard.tsx (hunk 2 above)
Comment (mxosman) [reply publisher/src/components/Home/TaskCard.tsx]: Ah right - thank you for clarifying!

**Comment by mxosman** [comment]
> @mxosman I also noticed that for the read only users we have task cards with `Manual Entry` buttons that lead us to `agency/:agencyID/records/:recordID` pages, where they actually can't manual entry anything, but can see already existed existed data. Maybe rename `Manual Entry` in this cases?

Good call - thank you for thinking of this! I thought about this too, and I think this is OK - as long as it leads them to the page, I'm fine with it for now continuing to operate as usual because they can still view the data. We'd also technically have this with the "Enter Data" link and the "Manual Entry" button when you go to the "Enter Data" page, but it's not worth adjusting all of those either. It's just the cases where they can't access the page that I think is worth addressing.

File: publisher/src/components/Home/TaskCard.tsx [hunk 3]
```diff
@@ -54,10 +55,15 @@ export const TaskCard: React.FC<{
...
+              isUserReadOnly &&
+              action.path === taskCardLabelsActionLinks.manualEntry.path &&
+              !recordID;
             const tooltipAnchorID =
-              action.path === "upload"
+              action.path === taskCardLabelsActionLinks.uploadData.path ||
+              isReadOnlyCreateRecordTaskCard
                 ? `${HomeStore.replaceSpacesAndParenthesesWithHyphen(
-                    title
+                    `${title}-${action.label}`
```
Comment (mxosman) [inline publisher/src/components/Home/TaskCard.tsx:66]: Nice!

**Review by mxosman — APPROVED** [review]
Awesome!! Thank you so much for this, Ilya! 🙏 Looks and feels great!

**Comment by nasaownsky** [comment]
> Good call - thank you for thinking of this! I thought about this too, and I think this is OK - as long as it leads them to the page, I'm fine with it for now continuing to operate as usual because they can still view the data. We'd also technically have this with the "Enter Data" link and the "Manual Entry" button when you go to the "Enter Data" page, but it's not worth adjusting all of those either. It's just the cases where they can't access the page that I think is worth addressing.

@mxosman Got it, thank you for clarification and for other great advices!
