### PR TITLE
[Publisher][Agency Settings] Fix data source questions bugs

### LINKED ISSUE #1599: [Publisher][Agency Settings] Address issues of the new biological sex and race & ethnicity data source questions
**What needs to be done? Why does it need to be done?**

1. User should be able to empty out a perviously saved value entered in the "Other" field.

https://github.com/user-attachments/assets/758be262-2847-4ee8-870a-025b793bc625

2. User should be able to uncheck a selection for a question.

https://github.com/user-attachments/assets/7848e309-d149-4670-b149-52cca5a5eff3

3. Empty out the fields and send the empty field to the BE when a user clicks away from the "Other"

4. Undo the capitalization for the options.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Fixed issues and bugs of data source questions

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

closes #1599 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Welcome back @mxosman! 

I moved all the issues you mentioned [here](https://github.com/Recidiviz/justice-counts/pull/1589#issuecomment-2504574365) into a separate task, if that's ok!

I also fix this part anyway:
>Empty out the fields and send the empty field to the BE when a user clicks away from the "Other"

File: publisher/src/components/AgencySettings/AgencySettingsDataSource.tsx [hunk 1]
```diff
@@ -164,16 +164,29 @@ const QuestionCheckboxBlock: React.FC<{
...
+      }
+      if (key !== "OTHER_AGENCY_OR_SYSTEM") {
+        updatedSetting[sourceType].modification.value = "";
+        if (key !== "OTHER") {
+          updatedSetting[sourceType].modification.other_description = "";
+        }
+      }
+      if (key !== "OTHER") {
+        updatedSetting[sourceType][settingType].other_description = "";
+      }
```
Comment (mxosman) [inline publisher/src/components/AgencySettings/AgencySettingsDataSource.tsx:185]: Can you help me understand this section here? I'm assuming it's wiping out the other fields?

So if I select the second choice in `What is the source of biological sex data in your system?`:
```
What is the source of biological sex data in your system?

[x] Data is collected directly by the agency
```

This will clear out the `collection_method` value?

Comment (mxosman) [reply publisher/src/components/AgencySettings/AgencySettingsDataSource.tsx:185]: Ah, I'm following now - would you mind adding a small comment here explaining what these conditionals are doing for posterity?
