### PR TITLE
[Publisher][Bug] Fix bug where Explore Data page shows first Combined Supervision datapoints when Supervision sector is disaggregated

### LINKED ISSUE #1629: [Publisher][Bug] Explore Data: Incorrectly displaying a disabled metric's charts
Bug Report from CSG: 

Agency 1474 in Publisher has a bug under the Explore Data Page for the Funding metric.

Problem: When I click on the Explore Data page, the Funding metric appears with data from CY2022 for Supervision. However, the agency turned off Supervision and is only reporting for Other Supervision (all of their metrics should be under Other Supervision).
When we click on the Explore Data page, we shouldn't see data for Supervision Funding. However, Publisher is showing us data for a metric that is turned off.

---

The issue is for Supervision sectors who have a Supervision (Combined) metric value in a report and later disaggregate it, the Explore Data page undesirably displays the first disabled Supervision (Combined) metric on load instead of the first enabled metric (which would be one of the disaggregated Supervision metrics, e.g. - Parole/Other Supervision/etc.)

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Fix bug where Explore Data page shows first Combined Supervision datapoints when Supervision sector is disaggregated. Bug was reported by CSG where an agency that has the Supervision sector disaggregated shows a Supervision Combined Funding metric's datapoints by default when first visiting the Explore Data page. This is caused by the current implementation relying on the `system` param which is `undefined` on load and subsequently gets set as the first agency's system instead of the first system with an enabled metric. 

The change proposed here sets the initial search params after initializing the report settings (our current way to infer the enabled/disabled status of a metric for now), which more accurately displays the charts for the first enabled metric and avoids the issue caused by the assumption that the first system in a user's agency includes an enabled metric. 

This component would benefit greatly from a deeper refactor to avoid future risk of race conditions with how we're retrieving metrics to determine the enabled/disabled status and how we're subsequently setting the search params. For now, this should unblock CSG and consistently produce the expected behavior until we can dedicate more time to exploring a more holistic refactor.

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #1629

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: publisher/src/components/DataViz/MetricsDataChart.tsx [hunk 1]
```diff
@@ -276,11 +276,34 @@ export const MetricsDataChart: React.FC = observer(() => {
...
+                              setSettingsSearchParams({
+                                system: system as AgencySystem,
+                                metric: metric.key,
+                              })
+                            }
+                          >
+                            {metric.display_name}
+                          </Styled.MetricItem>
+                        ))}
+                      </Styled.MetricsItemsContainer>
```
Comment (mxosman) [inline publisher/src/components/DataViz/MetricsDataChart.tsx:305]: Moves `MetricsItemsContainer` to the `currEnabledMetrics.length > 0` case so it doesn't show when there are no enabled metrics.

File: publisher/src/components/DataViz/MetricsDataChart.tsx [hunk 2]
```diff
@@ -167,6 +167,18 @@ export const MetricsDataChart: React.FC = observer(() => {
...
+      const refreshedEnabledMetrics = Object.values(result)
+        .flatMap((metric) => metric)
+        .filter((metric) => metric.enabled);
+      const firstEnabledSystemKey = refreshedEnabledMetrics[0]?.system.key;
+      const firstEnabledMetricKey = refreshedEnabledMetrics[0]?.key;
+
+      setSettingsSearchParams({
+        system: firstEnabledSystemKey,
+        metric: firstEnabledMetricKey,
+      });
```
Comment (mxosman) [inline publisher/src/components/DataViz/MetricsDataChart.tsx:181]: This is the biggest change - once we kick off initialization, we can update the params with the first enabled system and metric key, greatly simplifying the `currentSystem` and `currentMetric` logic in L102, 104 respectively.

Overall, this component still suffers a bit from the round-about way we're inferring the enabled metrics (querying the `ReportStore` instead of from the datapoints themselves), so a more holistic solution and refactor should be explored.

**Comment by helperbot-recidiviz** [comment]
@mxosman successfully triggered a playtest deployment. Full deployment usually takes 5 minutes. Your playtest link is https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/

**Review by danawillow — APPROVED** [review]
Stamping!

**Comment by mxosman** [comment]
Thank you, Dana!
