### PR TITLE
[Justice Counts] Fix data entry form bug when navigating back from publish confirm page

### LINKED ISSUE #152: [Frontend][Bug] Edit metric -> review and publish -> go back to data entry -> changes lost
@lilidworkin commented on [Wed Nov 09 2022](https://github.com/Recidiviz/recidiviz-data/issues/16570)

From Matt at CSG: "I got myself into a weird loop where when I tried to change a metric previously saved to a new number, then review and publish, then back to data entry, the metric reverts to the previously saved value" ([screen capture](https://csgorg-my.sharepoint.com/:v:/g/personal/mherman_csg_org/Efbj1Yo8JeBLiBxZ8qGD_WUBChTvPRN2GVqv50OJni8Wew?e=9DqJWZ))

---

@terryttsai commented on [Wed Nov 09 2022](https://github.com/Recidiviz/recidiviz-data/issues/16570#issuecomment-1309479428)

Thanks for the informative video capture! 

---

@lilidworkin commented on [Thu Nov 10 2022](https://github.com/Recidiviz/recidiviz-data/issues/16570#issuecomment-1310382086)

That was all from Matt actually! :D

### PR DESCRIPTION
**Pull request by terryttsai**
## Description of the change

See video for reproducing the bug here: https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/recidiviz/recidiviz-data/16570

This bug is caused by `formStore.validatePreviouslySavedInputs` being called when the user is navigating from the Publish Confirm page back to the data entry page, which replaces all user inputs with what was originally fetched from the server when the data entry page was first loaded.

The `DataEntryForm` component gets unmounted and remounted when navigating to and away from the Publish Confirm page, which causes `formStore.validatePreviouslySavedInputs` to get triggered. I believe `formStore.validatePreviouslySavedInputs` is intended to be triggered once on loading the data entry page and not when navigating from Publish Confirm back to the Data Entry Form.

My solution is to move the `formStore.validatePreviouslySavedInputs` trigger out of the `DataEntryForm` component and into the parent `ReportDataEntry` component. The parent component is loaded once when the data entry page is loaded, and calls `formStore.validatePreviouslySavedInputs`. It doesn't get called again until the user navigates away from the data entry section entirely. 

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #152

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: publisher/src/components/Reports/ReportDataEntry.tsx [hunk 1]
```diff
@@ -155,6 +154,13 @@ const ReportDataEntry = () => {
     []
   );
 
+  useEffect(() => {
+    /** Runs validation of previously saved inputs on load */
+    if (reportMetrics) {
+      formStore.validatePreviouslySavedInputs(reportID);
```
Comment (terryttsai) [inline publisher/src/components/Reports/ReportDataEntry.tsx:160]: Alternatively, we could also call this whenever a report is fetched? It could just be part of the process of fetching a report, storing it in the report store, and also storing inputs + validation in the form store?

Comment (lilidworkin) [reply publisher/src/components/Reports/ReportDataEntry.tsx:160]: That makes a lot of sense actually! I don't have strong feelings though -- if you feel that this solution is robust enough for now @terryttsai , I'm fine to merge this in as-is. Up to you.

**Review by lilidworkin — APPROVED** [review]
@terryttsai thank you so much for investigating this and for writing such a clear and well-explained PR description! This solution makes perfect sense to me. Curious what @mxosman thinks about your suggestion of moving this validation logic up to happen right after a report is fetched -- I'll leave it up to you both if you think that's worth doing now. I'm happy with this as-is though :)

File: publisher/src/components/Reports/ReportDataEntry.tsx (hunk 1 above)
Comment (mxosman) [reply publisher/src/components/Reports/ReportDataEntry.tsx:160]: No strong feelings either - both make a lot of sense! I'm good with your solution here!

**Review by mxosman — APPROVED** [review]
Nice debugging and solution, Terry!!

File: publisher/src/components/Reports/ReportDataEntry.tsx (hunk 1 above)
Comment (terryttsai) [reply publisher/src/components/Reports/ReportDataEntry.tsx:160]: I'll go with this for now!
