### PR TITLE
Fix selection behavior for "All records" and "Not started" tabs

### LINKED ISSUE #498: Records Page UI Refresh: Selection Behavior on All Records tab
We should enable or disable selection of records depending on the bulk action. In particular:
* Disable Published and Not Started records when you click Publish
* Disable Not Started and Draft when you click Unpublish

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Disable published and not_started records when action is Publish
Disable draft and not_started records when action is Unpublish
Disable Publish and Unpublish bulk actions when on Not Started tab

## Type of change
Type: Bug 

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #498

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
Hi Ivan! Can we extend the disabling of Publish/Unpublish behavior in the dropdown to the All Records tab for when one of those options is not possible? 

Example: 
* in a situation with 3 records (Not Started, Draft, Draft) and you are in the All Records tab, could `Unpublished` be disabled from the dropdown?
*  in a situation with 3 records (Not Started, Published, Published) or (Published, Published, Published) and you are in the All Records tab, could `Publish` be disabled from the dropdown?

File: publisher/src/pages/Reports.tsx [hunk 1]
```diff
@@ -435,15 +461,21 @@ const Reports: React.FC = () => {
                                 onClick={() => {
                                   selectBulkAction("publish");
                                 }}
-                                disabled={reportsFilter === "published"}
+                                disabled={
+                                  reportsFilter === "published" ||
+                                  reportsFilter === "not_started"
```
Comment (lilidworkin) [inline publisher/src/pages/Reports.tsx:466]: Good call on adding `not_started` to both of these!

**Review by lilidworkin — APPROVED** [review]
This looks great @ivan-kishko !

I think @mxosman 's suggestion is a great one -- thanks for suggesting that Mahmoud! I filed a task for it [here](https://github.com/Recidiviz/justice-counts/issues/534) and you can address it in a followup PR!
