### PR TITLE
Fix category page chart in recent mode

### LINKED ISSUE #831: Look into why there are 4 bars instead of 5 on the Agency page
Should be 5 bars, one for each year (and one should be missing, since this agency only has 4 years of data)

### PR DESCRIPTION
**Pull request by ivan-kishko**
## Description of the change

> Fix category page charts in recent mode to look like mini charts on agency page for consistency

## Type of change
Type: Non-breaking refactor

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes #831 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: agency-dashboard/src/CategoryOverview/CategoryOverview.tsx [hunk 1]
```diff
@@ -182,13 +186,11 @@ export const CategoryOverview = observer(() => {
...
                   <Styled.MetricDataVizContainer>
                     <MetricsCategoryBarChart
-                      data={filterDatapoints(
-                        transformDataForBarChart(
-                          agencyDataStore.datapointsByMetric[metric.key]
-                            .aggregate,
-                          DataVizTimeRangesMap.All,
-                          "Count"
-                        )
+                      data={transformDataForBarChart(
```
Comment (alfonsogoberjr) [inline agency-dashboard/src/CategoryOverview/CategoryOverview.tsx:189]: This will be affected by #810, specifically this part [here](https://github.com/Recidiviz/justice-counts/pull/810/files#diff-51ff4d22e39161ffdacfc0d4ad69243af7a86832415d0ed5afdfa2a95895b7ecR198) - this logic has been moved into a hook. 

Can you pull in the branch `792-part-2-capacity-and-costs-category` and update this PR?

**Review by alfonsogoberjr — CHANGES_REQUESTED** [review]

**Review by mxosman — APPROVED** [review]
LGTM!

**Review by mxosman — APPROVED** [review]

File: agency-dashboard/src/CategoryOverview/CategoryOverview.tsx (hunk 1 above)
Comment (ivan-kishko) [reply agency-dashboard/src/CategoryOverview/CategoryOverview.tsx]: [32f2c04](https://github.com/Recidiviz/justice-counts/pull/838/commits/32f2c0419307f44d27dfc1a2017748a1df00ddbb)

**Comment by ivan-kishko** [comment]
Sorry @mxosman I meant to ask for review from @alfonsogoberjr since he requested changes)

File: agency-dashboard/src/AgencyOverview/AgencyOverview.tsx [hunk 2]
```diff
@@ -227,18 +227,18 @@ export const AgencyOverview = observer(() => {
                             <MetricBoxGraphRange>
                               <span>
                                 {isAnnual
-                                  ? firstDatapointDate.getFullYear()
+                                  ? firstDatapointDate.getUTCFullYear()
```
Comment (alfonsogoberjr) [inline agency-dashboard/src/AgencyOverview/AgencyOverview.tsx:230]: good call using `Date.getUTCFullYear()`

File: agency-dashboard/src/CategoryOverview/CategoryOverview.tsx [hunk 3]
```diff
@@ -65,23 +65,28 @@ export const CategoryOverview = observer(() => {
...
   );
 
-  const filterDatapoints = useCallback(
-    (datapoints: Datapoint[]) => {
-      return dataRangeFilter === "recent" ? datapoints.slice(-5) : datapoints;
+  const getCurrentChartTimeRange = useCallback(
+    (isAnnual: boolean) => {
+      if (dataRangeFilter === "recent") {
+        return isAnnual
+          ? DataVizTimeRangesMap["5 Years Ago"]
```
Comment (alfonsogoberjr) [inline agency-dashboard/src/CategoryOverview/CategoryOverview.tsx:72]: Way better

**Review by alfonsogoberjr — APPROVED** [review]
