### PR TITLE
Fix loader position (make more consistent) between different settings pages

### LINKED ISSUE #355: [Frontend][Publisher] Fix loader position (make more consistent) in between the different settings pages
The loading animation appears in strange non-centered positions in all settings pages compared to the metric configuration page. It would be nice to have the loader appear in the same relative position. It stuck out when things were taking a little bit of time to load (when I was a new user) and ended up being a bit of an eye-sore. Not high priority but adding this issue so we can address it at some point!

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Fix loader position within the Agency Settings, Uploaded Files and Metric Configuration components in the Settings so that it is more uniform and consistent. Introduced a more specific loader `ContainedLoader` that will take up the width of the container it is in as opposed to the full width and height of the entire screen.

Before:

https://user-images.githubusercontent.com/59492998/216488172-4a256fd9-5d40-4c32-8586-a72ef0f5267b.mov

After:

https://user-images.githubusercontent.com/59492998/216488210-59d6dca1-3607-4470-b6a2-4029503d1631.mov

## Related issues

Closes #355 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: publisher/src/components/Loading/Loading.tsx [hunk 1]
```diff
@@ -40,6 +40,13 @@ const loadingSpriteAnimation = keyframes`
   }
 `;
 
+export const ContainedLoadingWrapper = styled.div`
+  width: 100%;
+  display: flex;
+  justify-content: center;
+  margin-top: 50px;
+`;
```
Comment (mxosman) [inline publisher/src/components/Loading/Loading.tsx:48]: We can always play with these values/create different positions - but this felt best for the settings page. I thought about adding `height: 100%` and `align-items: center` - and removing the `margin-top` but it felt like that made it sit awkwardly low on the page.

**Review by lilidworkin — APPROVED** [review]
I imagine this is uncontroversial, but cc @terryttsai in case he wants to take a look!
