### PR TITLE
[Agency Dashboard] Use same source of truth/calc for list of metrics between AgencyOverview and CategoryOverview

### LINKED ISSUE #897: [Bug][Frontend][Agency Dashboards] Handle incorrect URL paths and redirect to /404

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

`AgencyOverview` used the following logic to render the list of metrics:
```
            const metricsByCategory =
              agencyDataStore.metricsByCategory[category] || [];
            const metricsByCategoryBySystem = metricsByCategory.filter(
              (metric) => metric.system.key === currentSystem
            );
            ...
            const metricsWithData = metricsByCategoryBySystem.filter(
              (metric) =>
                agencyDataStore.datapointsByMetric[metric.key].aggregate.filter(
                  (dp) => dp[DataVizAggregateName] !== null
                ).length > 0
            );
```

Whereas `CategoryOverview` used the following logic:
```
  const categoryMetrics = useMemo(
    () =>
      categoryData[category]?.key
        ? agencyDataStore.metricsByCategory?.[categoryData[category]?.key]
        : [],
    [agencyDataStore.metricsByCategory, category]
  );
```

This created situations where `AgencyOverview` and `CategoryOverview` were rendering a different set of metrics (not entirely different - one loaded 4 metrics and the other loaded 3 metrics). 

This is a temporary solution (duplicating the logic in AgencyOverview to CategoryOverview) - in a pending refactor, there will be one source of truth for the set of metrics to render.

https://github.com/Recidiviz/justice-counts/assets/59492998/bd8ece6b-dfc0-4ece-b49c-f8ff93afa704

## Related Issues
Ad-hoc, also Closes #897 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by mxosman** [comment]
This is my last nit to prep Supervision [DEMO] and Prosecution [DEMO] for demos next week - after this adjustment, CSG should be all set for now!

File: agency-dashboard/src/CategoryOverview/CategoryOverview.tsx [hunk 1]
```diff
@@ -132,20 +133,20 @@ export const CategoryOverview = observer(() => {
...
+  return metricsWithData && categoryData[category] ? (
     <>
       <HeaderBar />
       <Styled.Wrapper>
         <Styled.Container>
           <Styled.TopBlock>
             <Button
               label="<- Home"
-              onClick={() => navigate(-1)}
+              onClick={() => navigate("..", { relative: "path" })}
```
Comment (mxosman) [inline agency-dashboard/src/CategoryOverview/CategoryOverview.tsx:149]: `navigate(-1)` takes you back to the previous page which is funky if you go directly to the CategoryOverview URL. This adjustments takes you up one level in the Route hierarchy (from `/agency/:slug/:category` to `/agency/:slug`) instead of whatever your previous page was. 

https://github.com/Recidiviz/justice-counts/assets/59492998/2fc9f2f7-8c3f-46be-8507-58198c0caa9b

**Comment by mxosman** [comment]
Sorry - one last side thing I'd like to slip in which is handling bad URL paths: [175aaab](https://github.com/Recidiviz/justice-counts/pull/900/commits/175aaabd33dadacfefc8bbef6ddc91a1c1a1fa8e)

It's super small - but I can break it out into another PR if that's preferable.

File: agency-dashboard/src/Protected/Protected.tsx [hunk 2]
```diff
@@ -39,8 +40,9 @@ export const Protected: React.FC<PropsWithChildren> = observer(
         await agencyDataStore.fetchAgencyData(slug as string);
         setLoading(false);
       } catch (error) {
+        navigate("/404");
         showToast({
-          message: "Error fetching data.",
+          message: `No agency found with slugline /${slug}.`,
```
Comment (mxosman) [inline agency-dashboard/src/Protected/Protected.tsx:45]: Meh? Any better quick copy for the toast?

File: agency-dashboard/src/CategoryOverview/CategoryOverview.tsx [hunk 3]
```diff
@@ -122,8 +114,17 @@ export const CategoryOverview = observer(() => {
   //   }
   // }, [getChartPng]);
 
+  const metricsByCategory =
```
Comment (lilidworkin) [inline agency-dashboard/src/CategoryOverview/CategoryOverview.tsx:117]: Just so I understand -- previously this page wasn't filtering out metrics with no data, but now it is? Good catch!

**Review by lilidworkin — APPROVED** [review]

File: agency-dashboard/src/CategoryOverview/CategoryOverview.tsx (hunk 3 above)
Comment (mxosman) [reply agency-dashboard/src/CategoryOverview/CategoryOverview.tsx:117]: Yeah - exactly!

**Comment by mxosman** [comment]
Thank you so much, Lili!
