### PR TITLE
[Publisher] Enable CSV download from Explore Data table view

### LINKED ISSUE #923: Downloading data from "Explore Data" table view is broken
I think it used to be the case that if you went to Explore Data, then clicked Switch to Data Table, and then clicked Download, it would download the data CSVs. Currently that link doesn't seem to do anything, though! Should be an easy fix since I know we already have the logic for getting the CSVs.

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Enables CSV download from Explore Data table view download button (which was only implemented in Agency Dashboards). Currently, the button does nothing in table view.

https://github.com/Recidiviz/justice-counts/assets/59492998/058fb138-536b-4fef-9cb4-16be31d84c78

## Related issues

Closes #923 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: agency-dashboard/src/DashboardView/DashboardView.tsx [hunk 1]
```diff
@@ -227,10 +226,14 @@ export const DashboardView = observer(() => {
...
-          downloadFeedData(metric.system.key, agencyDataStore.agency.id)
-        );
+        metric.filenames.forEach((filename) => {
+          if (agencyDataStore.agency)
+            downloadFeedData(
+              metric.system.key,
+              agencyDataStore.agency.id,
+              filename
+            );
+        });
```
Comment (mxosman) [inline agency-dashboard/src/DashboardView/DashboardView.tsx:236]: This entire component will be removed in #918 - feel free to skip this!

File: publisher/src/setupProxy.js [hunk 2]
```diff
@@ -19,7 +19,7 @@ const { createProxyMiddleware } = require("http-proxy-middleware");
 
 module.exports = function (app) {
   app.use(
-    ["/auth", "/api", "/app_public_config.js"],
+    ["/auth", "/api", "/feed", "/app_public_config.js"],
```
Comment (mxosman) [inline publisher/src/setupProxy.js:22]: This threw me for a loop for a minute there...

File: common/utils/downloadHelpers.ts [hunk 3]
```diff
@@ -15,11 +15,27 @@
...
+export const downloadMetricData = (
+  metric: Metric,
+  agencyId: number | string
+) => {
+  if (metric) {
+    metric.filenames.forEach((fileName) => {
+      downloadFeedData(metric.system.key, agencyId, fileName);
+    });
+  }
+};
```
Comment (mxosman) [inline common/utils/downloadHelpers.ts:41]: I just moved this to a more centralized location since both apps use this to download metric csv's - refactored slightly to accommodate.

File: publisher/src/components/DataViz/MetricsDataChart.tsx [hunk 4]
```diff
@@ -348,7 +349,9 @@ export const MetricsDataChart: React.FC = observer(() => {
             </Styled.PanelRightTopButton>
             <Styled.PanelRightTopButton
               onClick={() =>
-                handleChartDownload(currentSystem, currentMetric.key)
+                dataView === ChartView.Chart
```
Comment (lilidworkin) [inline publisher/src/components/DataViz/MetricsDataChart.tsx:352]: Yep this seems right to me!

File: publisher/src/setupProxy.js (hunk 2 above)
Comment (lilidworkin) [reply publisher/src/setupProxy.js:22]: Oh goodness haha, seriously, I would have never ...

**Review by lilidworkin — APPROVED** [review]
Awesome! Thanks for the quick fix and for consolidating code!
