### PR TITLE
[Fix] Replace EXCLUDED_SYSTEMS in Data Upload with SupervisionSubsystems

### LINKED ISSUE #386: [Frontend][Publisher] Fix DataUpload type error for multi-supervision agencies
Fix TypeError caused by using old `EXCLUDED_SYSTEMS` array in `DataUpload` component. Replace with `SupervisionSubsystems` which includes the latest list of supervision subsystems for the Data Upload component to exclude.

Screenshot 2023-02-03 at 6 47 51 PM

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Replacing the old `EXCLUDED_SYSTEMS` array that was a list of supervision subsystems with the `SupervisionSubsystems` constant to prevent a TypeError caught by @nichelle-hall (thank you for catching this!)

Screenshot 2023-02-03 at 6 47 51 PM

Test: https://nichelletest---justice-counts-web-qqec6jbn6a-uc.a.run.app/agency/153

Additionally, fixes the reference path to downloading templates from the UploadErrorsWarnings component.

## Related issues

Closes #386 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: publisher/src/components/DataUpload/UploadErrorsWarnings.tsx [hunk 1]
```diff
@@ -252,7 +252,7 @@ export const UploadErrorsWarnings: React.FC<UploadErrorsWarningsProps> = ({
           {selectedSystem && removeSnakeCase(selectedSystem).toLowerCase()}
         </span>{" "}
         system (
-        <a href={`./assets/${systemFileName}`} download={systemFileName}>
+        <a href={`/assets/${systemFileName}`} download={systemFileName}>
```
Comment (mxosman) [inline publisher/src/components/DataUpload/UploadErrorsWarnings.tsx:255]: The `./assets/...` made the reference be `URL.com/agency/{agencyID}/assets/TEMPLATE.xlsx` when it should be `URL.com/assets/TEMPLATE.xlsx`. Now users can properly download an example template from the UploadErrorsWarnings component.

Comment (lilidworkin) [reply publisher/src/components/DataUpload/UploadErrorsWarnings.tsx:255]: Oh nice, thanks for catching/fixing this!

**Review by lilidworkin — APPROVED** [review]
Great, thank you @mxosman ! Great teamwork with @nichelle-hall on debugging/fixing this!
