### PR TITLE
[Bug Bash] Data Page: Show the first enabled metric for an agency on load and handle no enabled metrics case

### LINKED ISSUE #523: [Frontend] Data: the first set of metrics for an agency that have enabled metrics should appear uncollapsed on load

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

The Data page currently shows a chart for the first metric (regardless of whether or not it is enabled/disabled) when a user loads the page. It also does not currently handle a case where no metrics are enabled. This PR allows a user to see the first _enabled_ metric on load, and when no metrics are enabled, the user sees a message with a link to the Metric Configuration page. 

Currently, when there are no metrics enabled, the user just sees a loader that never resolves. Does this new message screen feel jarring or does it feel like it works within this context? Open to all thoughts!

Before:

https://user-images.githubusercontent.com/59492998/231017800-92ea5000-bcad-44ca-a51c-09e0bc247c62.mov

After:

https://user-images.githubusercontent.com/59492998/231018789-fbcb4410-919d-4b7c-9db7-b4031a078868.mov

## Related issues

Closes #523 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: publisher/src/components/MetricConfiguration/MetricsView.tsx [hunk 1]
```diff
@@ -166,6 +169,22 @@ export const MetricsView: React.FC = observer(() => {
...
+      <NoEnabledMetricsMessage>
+        There are no enabled metrics to view. Please go to{" "}
+        <DisclaimerLink
+          onClick={() => {
+            navigate("../settings/metric-config");
+          }}
+        >
+          Metric Configuration
+        </DisclaimerLink>{" "}
+        to enable a metric.
```
Comment (mxosman) [inline publisher/src/components/MetricConfiguration/MetricsView.tsx:183]: Always open to better copy suggestions!

Comment (lilidworkin) [reply publisher/src/components/MetricConfiguration/MetricsView.tsx:183]: This looks great to me!

**Review by lilidworkin — COMMENTED** [review]
@mxosman when an agency has multiple systems, and there are enabled metrics in each system, can we uncollapse any system with enabled metrics? Currently I see this
Screenshot 2023-04-11 at 2 57 17 PM
which makes it looks like Jails has no enabled metrics, but it actually does. 

Also, the plus sign to expand the section doesn't appear until you hover over it - maybe it should always appear?
Screenshot 2023-04-11 at 2 57 57 PM

**Comment by mxosman** [comment]
> Do we anticipate running into the case where an agency uploads data for a metric, and then later on disables the metric? Probably unlikely, but I feel like in this event we might want to still show the data page for the disabled metric. If this is a concern, one solution could be showing metrics on the Data Page that actually have data, regardless of their enabled status.

Yes, I think that's definitely possible. If I'm understanding correctly - I think if an agency uploads data for a metric and that metric is enabled, they should see it in the Data page. If they later decide to disable the metric, it won't appear on the list (this was the regular behavior prior to this adjustment). I do like that solution if we want to change the behavior from only showing enabled metrics to only showing metrics with data! It does feel like a separate undertaking though that will take a bit more thought - but what you are saying totally makes sense!

**Comment by mxosman** [comment]
> @mxosman when an agency has multiple systems, and there are enabled metrics in each system, can we uncollapse any system with enabled metrics?

This ended up being a little trickier than I thought. After uncollapsing all the systems with enabled metrics, I realized the chart stretched vertically when there were a lot of enabled metrics on the list (I understand now the past decision to have an accordion style list of systems & metrics [one system open at a time]) - I made an adjustment to have the chart's max height be the viewport height.

I also made an adjustment to the logic that was displaying the first system & first enabled metric. It doesn't work well when there are multiple systems and the first system has no enabled metrics (e.g. a user w/ Prisons & Supervision systems -- Prisons is the first system in the list and has no enabled metrics, Supervision is the second system in the list and has enabled metrics -- the user ends up seeing "there are no enabled metrics" screen since the prev. logic is only grabbing the first system and its first enabled metrics). Now, we loop through all of the systems & their metrics and find the first enabled metric and display that on load. LMK if I'm not making sense here - happy to clarify further!


https://user-images.githubusercontent.com/59492998/231511540-e4e586d4-cd66-4089-b1c7-0b6b549cd0e7.mov


---
> Also, the plus sign to expand the section doesn't appear until you hover over it - maybe it should always appear?

After digging into this - I realized we don't actually need the + and hover cursor on the system names if everything is going to be uncollapsed when there are enabled metrics (and when there are no enabled metrics, there's nothing to uncollapse) -- so I removed the notion of the "+" sign and hover effect.
