### PR TITLE
[Publisher] Fix Download Data downloading blank CSVs in Explore Data page

### LINKED ISSUE #1435: [Publisher][Bug] Fix Download Data downloading blank CSVs in Explore Data page
There seems to be an issue with the `downloadMetricData` function in the Explore Data page where it is downloading a blank spreadsheet for all agencies. It looks like the `filenameWithAgencyName` being a part of the `url` in the `downloadFeedData` function is the root cause. The downloading works fine again if the `url` uses the `filename` without the agency name included.

If it's just the name of the file we want to include the agency's name in, then we can add another param to `downloadFeedData` that is the `filenameWithAgencyName`, and use the `filename` for the `url`, and the `filenameWithAgencyName` for the file name.

Relevant PR: https://github.com/Recidiviz/justice-counts/pull/1419

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Excluded `filenameWithAgencyName` from url in `downloadFeedData`

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

closes #1435 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: common/utils/downloadHelpers.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export const downloadFeedData = async (
     url = `/api${url}`;
   }
   a.href = url;
-  a.setAttribute("download", `${filenameWithAgencyName}.csv`);
+  a.setAttribute("download", `${filenameWithAgencyName ?? filename}.csv`);
```
Comment (mxosman) [inline common/utils/downloadHelpers.ts:40]: I like this fallback - but, I believe `filenameWithAgencyName` will always have a value here based on the expression in L53. Maybe we turn L55 to `undefined` - then if there's no agency name, `filenameWithAgencyName` will be undefined and it falls back to the `filename`. Otherwise, when there's no agency name, this will technically be `filename ?? filename`

**Review by mxosman — APPROVED** [review]
Thank you so much for taking care of this, Ilya! Works great again! Left a nit comment, but otherwise this should be good to go.
