### PR TITLE
[Bug Bash] Remove overlay on top of a metric's definitions when a metric has no availability set  

### LINKED ISSUE #525: When a time period hasn't been selected yet for a metric, don't grey out the definition
Right now, when a metric hasn't yet set the availability for a metric, the definition of the metric is greyed out on the right hand side. This might make it hard for them to decide whether or not they can report the metric (since they might want to read the definition before making that decision), so let's un-grey-it out!

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

When a metric's availability is in a `null` state (no selection has been made), the metric's title & description on the right panel are under an overlay that greys them out. This PR removes that overlay from the metric title & description so they are always visible.

**Before**
Screenshot 2023-04-10 at 5 48 31 PM

---

**After**

https://user-images.githubusercontent.com/59492998/231305555-895953f3-52ca-4902-9e9f-aabd6a45afd4.mov

## Related issues

Closes #525

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by lilidworkin** [comment]
Oh @mxosman sorry for being SO unclear in the task description -- I actually just meant like the text description of the metric, not the includes/excludes. Is it easy to remove the overlay just on that top part of the right side? If that's hard just LMK, not worth spending a ton of time on.

**Comment by mxosman** [comment]
> Oh @mxosman sorry for being SO unclear in the task description -- I actually just meant like the text description of the metric, not the includes/excludes. Is it easy to remove the overlay just on that top part of the right side? If that's hard just LMK, not worth spending a ton of time on.

Ohh - whoops! Haha - my bad! It shouldn't be hard to do - will make the adjustment. 🙌

File: publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx [hunk 1]
```diff
@@ -297,206 +298,213 @@ export const MetricBreakdownAvailabilityDefinitions: React.FC<MetricDefinitionsP
...
-                Confirm breakdown availability
-              </BreakdownAvailabilitySubTitle>
-              <BreakdownAvailabilityDescription>
-                Can you share data for this breakdown?
-              </BreakdownAvailabilityDescription>
-
-              <BreakdownAvailabilityMiniButtonWrapper>
-                <MiniButton
-                  selected={currentDimension?.enabled === false}
+          <OverlayWrapper enabled={metrics[systemMetricKey]?.enabled}>
```
Comment (mxosman) [inline publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx:309]: Nothing below here (aside from the closing `</OverlayWrapper>`) was changed. All indentation after adding an <OverlayWrapper>.
