### PR TITLE
[Bug] Metric Configuration: MetricBoxes Taking Up Entire Height

### LINKED ISSUE #125: [Frontend][Publisher] Metric Config - Metric Boxes taking up entire height [Bug]

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

Fixing the visual bug below where the MetricBoxes were taking up the entire height when there are 2 or less boxes. Did a manual test of each tab and other agencies and it no longer persists.

Before:
Screen Shot 2022-10-31 at 10 33 16 AM

After:
Screen Shot 2022-10-31 at 11 06 27 AM

## Related issues

Closes #125 

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: publisher/src/components/MetricConfiguration/MetricConfiguration.tsx [hunk 1]
```diff
@@ -525,17 +526,19 @@ export const MetricConfiguration: React.FC<{
...
-                  key={metric.key}
-                  metricKey={metric.key}
-                  displayName={metric.display_name}
-                  frequency={metric.frequency as ReportFrequency}
-                  description={metric.description}
-                  enabled={metric.enabled}
-                  setActiveMetricKey={setActiveMetricKey}
-                />
-              ))}
+              <MetricBoxContainerWrapper>
```
Comment (mxosman) [inline publisher/src/components/MetricConfiguration/MetricConfiguration.tsx:529]: Only change here was adding an extra wrapper `MetricBoxContainerWrapper`

**Review by lilidworkin — APPROVED** [review]
Looks good, thanks for catching!! Just for my own understanding, this doesn't really have to do with multi-system agencies, but rather when there are only a small number of metrics, right?

**Comment by mxosman** [comment]
> Looks good, thanks for catching!! Just for my own understanding, this doesn't really have to do with multi-system agencies, but rather when there are only a small number of metrics, right?

Yeah - you're absolutely right! Let me update that description.
