### PR TITLE
[Bug] Fix link from Help Center to Agency Dashboards for production users

### LINKED ISSUE #1067: [Bug] The dashboard guides in production link to the dashboard staging URL instead of prod URL

### PR DESCRIPTION
**Pull request by mxosman**
## Description of the change

I noticed a bug when I was playing around with the Help Center in production specifically in the link to Agency Dashboards. I was taken to the staging URL which resulted in an error - instead of the production URL. For some reason the piece of logic that creates the URL based on the environment isn't picking up on the right environment. I suspect it is because when this component is mounted, the `api.environment` is first `undefined` until it is set - and since these components aren't `observer`s they might not have been re-rendering when `api.environment` is set and have thus defaulted to the staging URL.

I tried to log the `api.environment` and deploy to playtesting with and without the `observer` and it logged `staging` for both - so my hunch might be off. But regardless, both components should be wrapped in an `observer` - so this change is necessary. I am curious to see when we deploy to prod if this fixes it. If not, I'll keep digging into this.

Screenshot 2023-11-20 at 11 28 27 AM

## Related issues

Closes #1067

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx [hunk 1]
```diff
@@ -16,13 +16,14 @@
...
 import { slugify } from "@justice-counts/common/utils";
+import { observer } from "mobx-react-lite";
 import React, { PropsWithChildren } from "react";
 
 import { useStore } from "../../stores";
 
 export const LinkToPublisher: React.FC<
   PropsWithChildren & { publisherPath: string }
-> = ({ publisherPath, children }) => {
+> = observer(({ publisherPath, children }) => {
```
Comment (mxosman) [inline publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx:26]: Wrapping these components in `observer` is the only change in this PR - the rest is prettier formatting.

**Comment by morden35** [comment]
> I tried to log the api.environment and deploy to playtesting with and without the observer and it logged staging for both - so my hunch might be off. But regardless, both components should be wrapped in an observer - so this change is necessary. I am curious to see when we deploy to prod if this fixes it. If not, I'll keep digging into this.

Yeah since playtesting links are technically staging, this makes sense. So hopefully this change is all that is needed once deployed to prod!

**Review by morden35 — APPROVED** [review]
lgtm!

**Comment by mxosman** [comment]
> > I tried to log the api.environment and deploy to playtesting with and without the observer and it logged staging for both - so my hunch might be off. But regardless, both components should be wrapped in an observer - so this change is necessary. I am curious to see when we deploy to prod if this fixes it. If not, I'll keep digging into this.
> 
> Yeah since playtesting links are technically staging, this makes sense. So hopefully this change is all that is needed once deployed to prod!

Thank you so much, Michelle! Yeah, I was hoping for the one without the `observer` to have logged twice - once `undefined` and the next one `staging`. 🤔 We shall find out next week!
